test: &default

  # Credentials for REST APIs
  client_id: AcAApgjbU1-rSVWnZ8nmThlgiFK6oSuQx4lgjiJpMuOaBFqXIH_v2bF57LutcQ4rvB5uQn5teKz-LtO5
  client_secret: EPs0XnScuQMOLmCdDY-X4m4_aGo9iTew-lK4qxZn03CdlbnsAe5Lz1xacu5iNEmWGp3MeB8QjXpct0BZ

  # Mode can be 'live' or 'sandbox'
  mode: sandbox

  # Credentials for Classic APIs
  app_id: APP-80W284485P519543T
  username: princybathla999_merchant_api1.yahoo.com
  password: K87Q78CAFUMMSAPY
  signature: AFcWxV21C7fd0v3bYYYRCpSSRl31AVjmCwS0tpqs0XTsREx47661EbyT
  # # With Certificate
  # cert_path: "config/cert_key.pem"
  sandbox_email_address: princybathla999_merchant@yahoo.com

  # # IP Address
  # ip_address: 127.0.0.1
  # # HTTP Proxy
  # http_proxy: http://proxy-ipaddress:3129/

development:
  <<: *default

production:
  <<: *default
  mode: live
